Bump qdigidoc4 to 4.4.0 with added depencendy on flatbuffers
open-eid/gentoo pull request #65
Opened 2024-01-17 11:12 UTC by mattiasMerilai

Signed-off-by: Firstname Lastname <firstname.lastname@example.com>

2024-02-08 22:47 UTC, monoidic commented
You can just drop the version specifiers from `dev-libs/opensc` and `dev-libs/libdigidocpp` because only acceptable versions are available now. The `append-cppflags "-DOF=_Z_OF"` is also dead becase a) this macro rename [was dropped by Gentoo](https://bugs.gentoo.org/383179), and b) it does not seem like `OF()` is in use in qdigidoc4 anyhow. If it was, then this would actually cause build failures., as `_Z_OF` is undefined.

2024-02-08 23:02 UTC, mattiasMerilai commented
Sorted.

2024-02-09 00:21 UTC, monoidic commented
Something else I forgot to add - run `pkgdev manifest` to generate the required line in the manifest file.

2024-02-09 00:32 UTC, mattiasMerilai commented
Oh yeah, here you go.

2024-03-19 08:47 UTC, jaakristioja commented
https://github.com/open-eid/DigiDoc4-Client/commit/e08c566a7426d04ca6549a73a25a1fe41eb0ab7a which added the dependency on FlatBuffers, also added the dependency on zlib, so `sys-libs/zlib` should also be added to `RDEPEND`. 

Otherwise, looks fine to me.

2024-06-17 07:26 UTC, metsma requested changes

2024-06-17 07:26 UTC, metsma commented on app-crypt/qdigidoc4/qdigidoc4-4.4.0.ebuild
> +	sed -i 's/ Qt6 / /' CMakeLists.txt # configure fails if Qt6 is installed
Qt6 should be preferred

2024-06-17 07:26 UTC, metsma commented on app-crypt/qdigidoc4/qdigidoc4-4.4.0.ebuild
> +	eapply --fuzz=3 "${FILESDIR}/sandbox-compat.patch"
Can we update the configuration files

2025-05-02 08:52 UTC, lkraav commented
1 year later, has this PR become completely stale or could be refreshed for latest upstream version?

2025-05-10 16:19 UTC, mattiasMerilai commented
Updated ebuilds.

2025-05-12 18:03 UTC, lkraav commented on app-crypt/qdigidoc4/Manifest
> +>>>>>>> 5d4beeb (Dropped old packages. Bumped libdigidocpp and qdigidoc4 to current versions. Updated qdigidoc4 to build against qt6 instead of qt5.)
`Manifest` conflict resolution is incomplete?

2025-05-12 18:03 UTC, lkraav commented on app-crypt/qdigidoc4/qdigidoc4-4.6.1.ebuild
Do we need to keep 4.6.1 in play at all?

2025-05-12 18:03 UTC, lkraav commented on app-crypt/qdigidoc4/qdigidoc4-4.7.0.ebuild
Kinda curious about PN `qdigidoc4` what happens when it reaches v5?

2025-05-12 18:03 UTC, lkraav commented on dev-libs/libdigidocpp/libdigidocpp-4.0.0.ebuild
Why keep 4.0.0 ebuild?

2025-05-14 06:58 UTC, mattiasMerilai commented on app-crypt/qdigidoc4/Manifest
> +>>>>>>> 5d4beeb (Dropped old packages. Bumped libdigidocpp and qdigidoc4 to current versions. Updated qdigidoc4 to build against qt6 instead of qt5.)
sorted

2025-05-14 07:00 UTC, mattiasMerilai commented on app-crypt/qdigidoc4/qdigidoc4-4.6.1.ebuild
not necessarily

2025-05-14 07:00 UTC, mattiasMerilai commented on app-crypt/qdigidoc4/qdigidoc4-4.7.0.ebuild
the same that happens to upstream package name?

2025-05-14 07:00 UTC, mattiasMerilai commented on dev-libs/libdigidocpp/libdigidocpp-4.0.0.ebuild
not much reason ig

2025-05-14 08:00 UTC, merged

2025-05-14 08:07 UTC, metsma commented on profiles/repo_name
> +esteid-mattias
Is this ideational?

2025-05-14 08:07 UTC, metsma commented on profiles/package.unmask
>  =dev-cpp/libxsd-frontend-2.0.0-r1
The other packages can also be removed

2025-05-14 08:12 UTC, mattiasMerilai commented on profiles/repo_name
> +esteid-mattias
sorry about that

2025-05-14 08:28 UTC, mattiasMerilai commented on profiles/package.unmask
>  =dev-cpp/libxsd-frontend-2.0.0-r1
libdigidocpp-9999 is still depending on them, possibly broken? i'll look into updating it.

2025-05-14 09:05 UTC, metsma commented on profiles/package.unmask
>  =dev-cpp/libxsd-frontend-2.0.0-r1
Updated my PR #61

2025-05-14 09:24 UTC, urmet commented
`qdigidoc4/files/qt6only.patch` is missing

2025-05-14 09:30 UTC, mattiasMerilai commented
Just one of these days...
I already went afk for the day. Will get to this in the evening.

On Wed, May 14, 2025, 12:25 urmet ***@***.***> wrote:

> *urmet* left a comment (open-eid/gentoo#65)
> <https://github.com/open-eid/gentoo/pull/65#issuecomment-2879476870>
>
> qdigidoc4/files/qt6only.patch is missing
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/open-eid/gentoo/pull/65#issuecomment-2879476870>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2LIIU3UPN6W4FSE2LUHM5L26MDYDAVCNFSM6AAAAAB4JSIEIGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDQNZZGQ3TMOBXGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-05-14 19:17 UTC, mattiasMerilai commented
> `qdigidoc4/files/qt6only.patch` is missing

sorted

2025-05-15 09:05 UTC, lkraav commented
> You can just drop the version specifiers from dev-libs/opensc and dev-libs/libdigidocpp because only acceptable versions are available now.

This idea fails when upgrading existing systems? Old `dev-libs/libdigidocpp` is already installed, and upgrade is not pulled in.

```
θ69° 1d [leho@gusto:~]└2 1 $ sudo emerge -va1g qdigidoc4

[binary  N     ] dev-libs/flatbuffers-25.2.10-1:0/25.2.10::gentoo  USE="-static-libs -test" 1 220 KiB
[ebuild     U ~] app-crypt/qdigidoc4-4.7.0::esteid [4.3.0::esteid] 3 985 KiB

Total: 2 packages (1 upgrades, 1 new, 1 binary).
```

2025-05-17 16:16 UTC, mattiasMerilai commented
> `qdigidoc4/files/qt6only.patch` is missing

just in case - https://github.com/open-eid/gentoo/pull/68